<template>
  <v-container>
    <v-card class="pa-3">
      <v-row dense>
        <v-col
          cols="auto"
        >
          <v-card
            class="pa-3"
            outlined
          >
            col
          </v-card>
        </v-col>
        <v-col>
          <v-card
            class="pa-3"
            outlined
          >
            col
          </v-card>
        </v-col>
        <v-col>
          <v-card
            class="pa-3"
            outlined
          >
            col
          </v-card>
        </v-col>
      </v-row>
      <v-row>
        <v-col>
          <v-card
            class="pa-3"
            outlined
          >
            col
          </v-card>
        </v-col>
        <v-col>
          <v-card
            class="pa-3"
            outlined
          >
            col
          </v-card>
        </v-col>
        <v-col>
          <v-card
            class="pa-3"
            outlined
          >
            col
          </v-card>
        </v-col>
      </v-row>
    </v-card>

    <v-card class="mt-5 pa-3">
      <v-row>
        <v-col>
          <v-card
            class="pa-3"
            outlined
          >
            col
          </v-card>
        </v-col>
        <v-col>
          <v-card
            class="pa-3"
            outlined
          >
            col
          </v-card>
        </v-col>
        <v-spacer />
        <v-col>
          <v-card
            class="pa-3"
            outlined
          >
            col
          </v-card>
        </v-col>
      </v-row>
      <v-row>
        <v-spacer />
        <v-col>
          <v-card
            class="pa-3"
            outlined
          >
            col
          </v-card>
        </v-col>
        <v-col>
          <v-card
            class="pa-3"
            outlined
          >
            col
          </v-card>
        </v-col>
        <v-col>
          <v-card
            class="pa-3"
            outlined
          >
            col
          </v-card>
        </v-col>
      </v-row>
    </v-card>

    <v-card class="mt-5 pa-3">
      <v-row
        :style="{height: '120px'}"
        class="red"
        align="start"
      >
        <v-col>
          <v-card
            class="pa-3"
            outlined
          >
            col
          </v-card>
        </v-col>
        <v-col>
          <v-card
            class="pa-3"
            outlined
          >
            col
          </v-card>
        </v-col>
        <v-col>
          <v-card
            class="pa-3"
            outlined
          >
            col
          </v-card>
        </v-col>
      </v-row>
      <v-row
        :style="{height: '120px'}"
        class="yellow"
      >
        <v-col align-self="end">
          <v-card
            class="pa-3"
            outlined
          >
            col
          </v-card>
        </v-col>
        <v-col align-self="center">
          <v-card
            class="pa-3"
            outlined
          >
            col
          </v-card>
        </v-col>
        <v-col>
          <v-card
            class="pa-3"
            outlined
          >
            col
          </v-card>
        </v-col>
      </v-row>
    </v-card>

    <v-card class="mt-5 pa-3">
      <v-row justify="space-around">
        <v-col
          cols="auto"
        >
          <v-card
            class="pa-3"
            outlined
          >
            col
          </v-card>
        </v-col>
        <v-col
          cols="auto"
        >
          <v-card
            class="pa-3"
            outlined
          >
            col
          </v-card>
        </v-col>
        <v-col
          cols="auto"
        >
          <v-card
            class="pa-3"
            outlined
          >
            col
          </v-card>
        </v-col>
      </v-row>
    </v-card>
  </v-container>
</template>

<script>
export default {

}
</script>
